# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contest < Formula
  desc "A simple tool for contract testing web APIs"
  homepage "https://www.github.com/cadast/contest"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cadast/contest/releases/download/v1.1.0/contest_1.1.0_macOS_arm64.tar.gz"
      sha256 "9764997bbd8a82224be2dff3fbf3af8d4e9ef929d01b7a8d52681a0983c62477"

      def install
        bin.install "contest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cadast/contest/releases/download/v1.1.0/contest_1.1.0_macOS_x86_64.tar.gz"
      sha256 "ca714c0693cddd76f5096ae43e9990d69b04026ce958db90e03157996264b662"

      def install
        bin.install "contest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cadast/contest/releases/download/v1.1.0/contest_1.1.0_linux_x86_64.tar.gz"
      sha256 "0bf5a3b96fbad20c3ea92851354d9f657e4a0bfb1bae10f3c475cc316e5d2d7e"

      def install
        bin.install "contest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cadast/contest/releases/download/v1.1.0/contest_1.1.0_linux_arm64.tar.gz"
      sha256 "4e7fe5dd7a1561a2476281b1d8f2e5abeaa884172342f40c48d2a1ae8cb938ee"

      def install
        bin.install "contest"
      end
    end
  end
end
