# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contest < Formula
  desc ""
  homepage "https://www.github.com/cadast/contest"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "git@github.com:cadast/contest/releases/download/v1.0.0/contest_1.0.0_macOS_arm64.tar.gz", :using => GitDownloadStrategy
      sha256 "24ee3075eb0e8dd42169db80c5a27d8b0bfb3c79ba39afeb821f3e2b51a5cef9"

      def install
        bin.install "contest"
      end
    end
    if Hardware::CPU.intel?
      url "git@github.com:cadast/contest/releases/download/v1.0.0/contest_1.0.0_macOS_x86_64.tar.gz", :using => GitDownloadStrategy
      sha256 "4d3028d21683c45409027bf4e6de7ea5d2f1124a6ec833cbbe6a801f9c18c1e3"

      def install
        bin.install "contest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "git@github.com:cadast/contest/releases/download/v1.0.0/contest_1.0.0_linux_arm64.tar.gz", :using => GitDownloadStrategy
      sha256 "9ee1c8de4101f4c22bff47f696e1bdcba53cd37649916ae0d8932349b7992fcb"

      def install
        bin.install "contest"
      end
    end
    if Hardware::CPU.intel?
      url "git@github.com:cadast/contest/releases/download/v1.0.0/contest_1.0.0_linux_x86_64.tar.gz", :using => GitDownloadStrategy
      sha256 "bd68c391ac3b395d61b3357784388d99d1837328403bc3a114ebe3dcea533636"

      def install
        bin.install "contest"
      end
    end
  end
end
